=== bettyblocks/json-schema/schemas/actions/function.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://raw.githubusercontent.com/bettyblocks/json-schema/edge/schemas/actions/function.json",
  "title": "Function",
  "description": "A function to be used in the IDE",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "expression": {
      "description": "Indicates if the function is an expression or normal function",
      "type": "boolean",
      "default": false
    },
    "label": {
      "description": "The label for the function, as shown in the IDE",
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "category": {
      "description": "The category by which the functions are grouped and shown in the sidebar.",
      "type": "string"
    },
    "icon": {
      "__comment": "The available icons are defined by a set we have available in our framework.",
      "description": "The icon to be displayed in the IDE for this function.",
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "name": {
          "type": "string"
        },
        "color": {
          "enum": [
            "Yellow",
            "Green",
            "Pink",
            "Orange",
            "Purple",
            "Blue",
            "Teal",
            "Grey"
          ]
        }
      },
      "required": ["name", "color"]
    },
    "context": {
      "description": "Determines the context in which the function is utilized, thereby offering context-specific options.",
      "type": "array",
      "uniqueItems": true,
      "items": {
        "enum": ["gqlBuffer"]
      }
    },
    "options": {
      "description": "The options that you want configured for the action. These can be referred by name inside the function",
      "type": "array",
      "items": {
        "$ref": "/bettyblocks/json-schema/edge/schemas/actions/function/option.json"
      }
    },
    "paths": {
      "description": "The paths that you want configured for the action step.",
      "type": "object",
      "$ref": "/bettyblocks/json-schema/edge/schemas/actions/function/paths.json"
    },
    "yields": {
      "description": "Determines whether the function can have other functions nested and if so, what the behaviour should be for executing those functions",
      "enum": ["NONE", "PATHS", "ALL"]
    },
    "wasmDescription": {
      "description": "WebAssembly function description",
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "functionName": {
          "type": "string",
          "description": "The name of the function that is exported in the wit file"
        },
        "interface": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "name": {
              "description": "The name of the interface set in the wit file",
              "type": "string"
            },
            "package": {
              "description": "The name of the package defined in the wit file, like: example:my-package@0.1.0",
              "type": "string"
            }
          },
          "required": ["name", "package"]
        }
      },
      "required": ["functionName", "interface"]
    }
  },
  "anyOf": [
    {
      "properties": {
        "yields": { "const": "PATHS" }
      },
      "required": ["paths"]
    },
    {
      "properties": {
        "yields": { "enum": ["ALL", "NONE"] },
        "paths": false
      }
    }
  ],
  "required": ["label", "description", "category", "icon", "yields"]
}

=== bettyblocks/json-schema/examples/functions/subaction/function.json
{
  "description": "Execute a Subaction",
  "label": "Subaction",
  "category": "CRUD",
  "icon": {
    "name": "ActionIcon",
    "color": "Orange"
  },
  "options": [
    {
      "meta": {
        "type": "Action",
        "validations": {
          "required": true
        }
      },
      "name": "action",
      "label": "Action",
      "info": "The action you want to execute."
    },
    {
      "meta": {
        "type": "InputVariableMap",
        "action": "action"
      },
      "name": "inputMapping",
      "label": "Input Variable Mapping",
      "info": "Mapping of values to input variables for the action. The input variables are based on the selected action.",
      "configuration": {
        "dependsOn": [
          {
            "option": "action",
            "action": "CLEAR"
          }
        ]
      }
    }
  ],
  "yields": "NONE"
}

=== bettyblocks/json-schema/examples/functions/condition/function.json
{
  "description": "Change the way the flow executes",
  "label": "Condition",
  "category": "Flow",
  "icon": {
    "name": "ConditionIcon",
    "color": "Yellow"
  },
  "yields": "PATHS",
  "paths": {
    "min": 1,
    "max": 1,
    "filterOption": {
      "meta": {
        "type": "Value",
        "allowedKinds": ["BOOLEAN"],
        "validations": {
          "required": true
        }
      },
      "name": "value",
      "label": "Value",
      "info": "If this value is evaluated truthy the child steps will be executed."
    },
    "values": [
      {
        "label": "Branch 1"
      }
    ]
  }
}
